name: MLflow CI Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v3
        with:
          python-version: 3.10
          auto-update-conda: true
          activate-environment: mlflow
          environment-file: MLProject/environment.yml
          use-mamba: true

      - name: Install MLflow
        run: |
          conda activate mlflow
          pip install mlflow

      - name: Run MLflow Project
        run: |
          conda activate mlflow
          cd MLProject
          mlflow run . --env-manager=conda

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: ~/.mlflow

      - name: Build Docker Image with MLflow
        run: |
          cd MLProject
          mlflow build-docker -n ${{ secrets.DOCKER_USERNAME }}/bbc-news-mlflow

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bbc-news-mlflow
